import api from "../../services/api";

export const fetchAiReportSummary = async (patientId) => (await api.get(`/ai/report-summary/${patientId}`)).data;
export const exportAiReportSummary = async (patientId) => (await api.post(`/ai/report-summary/export/${patientId}`)).data;
export const fetchAiRiskPrediction = async (patientId) => (await api.get(`/ai/risk-prediction/${patientId}`)).data;
export const fetchAiTreatmentRecommendations = async (patientId) => (await api.get(`/ai/treatment-recommendations/${patientId}`)).data;
export const sendMentalHealthChat = async (payload) => (await api.post("/ai/mental-health/chat", payload)).data;
export const runMentalHealthAssessment = async (payload) => (await api.post("/ai/mental-health/assessment", payload)).data;
export const startVoiceIntake = async (payload) => (await api.post("/ai/voice-intake/start", payload)).data;
export const processVoiceIntake = async (payload) => (await api.post("/ai/voice-intake/process", payload)).data;
export const finalizeVoiceIntake = async (payload) => (await api.post("/ai/voice-intake/finalize", payload)).data;
export const fetchAiAdherenceCoach = async (patientId) => (await api.get(`/ai/insights/adherence/${patientId}`)).data;
export const fetchAiHealthTrends = async (patientId) => (await api.get(`/ai/insights/health-trends/${patientId}`)).data;
export const fetchAiFollowUp = async (patientId) => (await api.get(`/ai/insights/follow-up/${patientId}`)).data;
export const fetchAiJourneyPlan = async (patientId) => (await api.get(`/ai/insights/journey/${patientId}`)).data;
export const fetchDoctorRiskQueue = async (doctorId) => (await api.get(`/ai/insights/risk-queue/doctor/${doctorId}`)).data;
export const fetchCaregiverPriorityQueue = async (caregiverId) => (await api.get(`/ai/insights/caregiver/priority-queue/${caregiverId}`)).data;
export const fetchBehavioralDeviations = async (patientId) => (await api.get(`/ai/insights/caregiver/deviations/${patientId}`)).data;
export const fetchCheckInScript = async (patientId) => (await api.get(`/ai/insights/caregiver/checkin-script/${patientId}`)).data;
export const fetchConsultationSummary = async (consultationId) => (await api.get(`/ai/insights/consultation-summary/${consultationId}`)).data;
export const fetchDifferentialSuggestions = async (payload) => (await api.post("/ai/insights/differential-suggestions", payload)).data;
export const fetchDrugInteractions = async (payload) => (await api.post("/ai/insights/drug-interactions", payload)).data;
export const fetchRefillPrediction = async (pharmacistId) => (await api.get(`/ai/insights/pharmacy/refill-prediction/${pharmacistId}`)).data;
export const fetchInventoryRisk = async (pharmacistId) => (await api.get(`/ai/insights/pharmacy/inventory-risk/${pharmacistId}`)).data;
export const fetchSubstitutionSuggestions = async (payload) => (await api.post("/ai/insights/pharmacy/substitutions", payload)).data;
export const logMoodEntry = async (patientId, payload) => (await api.post(`/ai/insights/mood/${patientId}`, payload)).data;
export const fetchMoodEntries = async (patientId) => (await api.get(`/ai/insights/mood/${patientId}`)).data;
export const fetchMoodTrends = async (patientId) => (await api.get(`/ai/insights/mood/${patientId}/trends`)).data;
export const fetchStressRecommendations = async (patientId) => (await api.get(`/ai/insights/stress-recommendations/${patientId}`)).data;

export const generateSoapNote = async (payload) => (await api.post("/intelligence/doctor/scribe", payload)).data;
export const checkClinicalDrugInteractions = async (payload) => (await api.post("/intelligence/doctor/drug-interactions", payload)).data;
export const calculateDosage = async (payload) => (await api.post("/intelligence/doctor/dosage", payload)).data;
export const suggestClinicalAlternatives = async (payload) => (await api.post("/intelligence/doctor/alternatives", payload)).data;
export const askCopilot = async (payload) => (await api.post("/intelligence/doctor/copilot", payload)).data;
export const extractPrescriptionFromImage = async (formData) => (await api.post("/intelligence/doctor/ocr", formData, { headers: { "Content-Type": "multipart/form-data" } })).data;
export const transcribeAudioToSoapNote = async (formData) => (await api.post("/intelligence/doctor/scribe/audio", formData, { headers: { "Content-Type": "multipart/form-data" } })).data;
