apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: telecare-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - telecare.example.com
    secretName: telecare-tls
  rules:
  - host: telecare.example.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: telecare-backend-service
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: telecare-backend-service
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: telecare-frontend-service
            port:
              number: 80
