spring.jpa.show-sql=${TELECARE_SHOW_SQL:true}
spring.jpa.hibernate.ddl-auto=${TELECARE_JPA_DDL_AUTO:update}

app.jwt.secret=${TELECARE_JWT_SECRET:telecareplus-super-secure-academic-secret-key-telecareplus}
app.auth.otp.demo-mode=${TELECARE_OTP_DEMO_MODE:true}
