-- jOOQ codegen schema - H2-compatible DDL only.
-- This file is NOT a Flyway migration. It mirrors the JPA entity structure
-- so that jOOQ can generate type-safe table classes for use in query components.
-- Keep in sync with the JPA @Entity definitions when schema changes are made.

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name   VARCHAR(255),
    role        VARCHAR(50),
    active      BOOLEAN DEFAULT TRUE,
    email_notifications_enabled  BOOLEAN,
    sms_notifications_enabled    BOOLEAN,
    push_notifications_enabled   BOOLEAN
);

CREATE TABLE IF NOT EXISTS patients (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    diseases    VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS doctors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    specialty   VARCHAR(100),
    experience_years    INT,
    consultation_fee    NUMERIC(10,2)
);

CREATE TABLE IF NOT EXISTS caregivers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT
);

CREATE TABLE IF NOT EXISTS patient_caregiver_link (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      BIGINT,
    caregiver_id    BIGINT,
    caregiver_user_id BIGINT,
    active          BOOLEAN,
    created_at      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id              BIGINT,
    doctor_id               BIGINT,
    appointment_date_time   TIMESTAMP,
    status                  VARCHAR(50),
    triage_assessment_id    BIGINT,
    concern_summary         VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS prescriptions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  BIGINT,
    doctor_id   BIGINT,
    notes       VARCHAR(1000),
    created_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS medication_reminders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      BIGINT,
    scheduled_date  TIMESTAMP,
    status          VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS health_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      BIGINT,
    blood_pressure  VARCHAR(20),
    sugar           NUMERIC(6,2),
    spo2            NUMERIC(5,2),
    alert_severity  VARCHAR(50),
    recorded_at     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS triage_assessments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      BIGINT,
    level           VARCHAR(100),
    recommendation  VARCHAR(1000),
    assessed_at     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS consultation_notes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      BIGINT,
    doctor_id       BIGINT,
    outcome         VARCHAR(100),
    notes           TEXT,
    follow_up_date  DATE,
    created_at      TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  BIGINT,
    severity    VARCHAR(50),
    message     VARCHAR(1000),
    active      BOOLEAN,
    created_at  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS care_plans (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  BIGINT,
    active      BOOLEAN
);

CREATE TABLE IF NOT EXISTS medication_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id BIGINT,
    medicine_name   VARCHAR(255),
    dosage          VARCHAR(100),
    frequency       VARCHAR(100)
);
